seed_everything: 3407  # https://arxiv.org/abs/2109.08203
trainer:
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  # strategy:
  #   class_path: pytorch_lightning.strategies.DeepSpeedStrategy
  #   init_args:
  #     stage: 2
  #     offload_optimizer: false
  #     cpu_checkpointing: false
  # strategy:
  #   class_path: pytorch_lightning.strategies.FSDPStrategy
  #   init_args:
  #     stage: 2
  #     offload_optimizer: false
  #     cpu_checkpointing: false
  gradient_clip_val: 1.0
  callbacks:
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        verbose: true
        save_top_k: 1
        save_last: true
        monitor: val/Recall@10
        mode: max
  # max_steps: 200000
  max_epochs: 2
  # check_val_every_n_epoch: 1
  check_val_every_n_epoch: 2
  limit_val_batches: 5000
  num_sanity_val_steps: 0

  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: lean-colbert

model:
  config:
    checkpoint: bert-base-uncased
    collection: ../../../data/msmarco/collection_small.hf
    index_name: bert
    experiment: msmarco
    root: ../../../experiments/
    warmup: 10000  # 20000
    lr: 1e-5
    num_retrieved: 100
    n_log_premises: 10
    query_maxlen: 96
    doc_maxlen: 180
    mask_punctuation: false
    debug: false
    ignore_scores: true
    num_negatives: 1
    num_in_file_negatives: 1
    nway: -1

    # nprobe: 2
    # ncandidates: 8192
    index_bsize: 128
    nbits: 1
    kmeans_niters: 20
    resume: false
    similarity: cosine
    relu: false
    use_ib_negatives: false
    drop_duplciate_passages: false
    reranker: false
    distillation_alpha: 1.0
    attend_to_mask_tokens: false
    interaction: colbert
    dim: 128
    overwrite: false

data:
  data_dir: ../../../data/msmarco/triples_small.hf
  batch_size: 24  # training batch size
  eval_batch_size: 200 # the batch size will be used for corpus reindexing
  num_workers: 1
